Repository eldon-chung/raccoon-editor, pull requests merged in 2020-06, with the labels that each got.

#28 Implement piece table for Buffer struct [Part 3]
  src/model/app.rs
  src/model/buffer.rs
  src/model/cursor.rs
  src/model/mod.rs
  src/model/nodelist.rs
  src/model/tests/buffer_tests.rs
  src/model/tests/nodelist_tests.rs
  src/utils/mod.rs
Labels: enhancement

#30 Cursor movement bugfix
  src/main.rs
  src/model/app.rs
  src/model/buffer.rs
  src/model/tests/buffer_tests.rs
Labels: bug

#33 Update issue templates and include labels in it
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: misc

#25 Implement file opening and saving
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/main.rs
  src/model/app.rs
  src/model/tests/app_tests.rs
  src/view/mod.rs
Labels: feature request

#35 Implement text tags
  src/main.rs
  src/model/app.rs
  src/model/buffer.rs
  src/model/mod.rs
  src/model/taggedtext.rs
  src/model/tests/app_tests.rs
  src/model/tests/buffer_tests.rs
  src/model/texttag.rs
  src/view/mod.rs
Labels: feature request
