Repository eldon-chung/raccoon-editor, pull requests merged in 2020-05, with the labels that each got.

#6 implement left/right cursor movement
  src/main.rs
  src/model/app.rs
  src/model/buffer.rs
Labels: feature request

#10 Implement piece table for Buffer struct [Part 1]
  src/model/app.rs
  src/model/buffer.rs
  src/model/tests/buffer_tests.rs
  src/utils/mod.rs
  src/view/mod.rs
Labels: enhancement

#9 Update build automation tools
  .travis.yml
  src/lib.rs
Labels: misc

#12 Fix travis config for codecov
  .travis.yml
Labels: bug fix

#14 Add badges for travis build and codecov
  README.md
Labels: misc

#15 Run all test executables in Travis CI
  .travis.yml
Labels: misc

#20 Implement piece table for Buffer struct [Part 2]
  src/model/buffer.rs
  src/model/tests/buffer_tests.rs
  src/utils/mod.rs
Labels: enhancement

#21 Configure codecov to ignore test files
  .codecov.yml
Labels: misc

#22 $elax threshold for Codecov project status
  .codecov.yml
Labels: misc

#23 Change indentation of all files from tabs to spaces
  src/main.rs
  src/model/app.rs
  src/model/buffer.rs
  src/model/tests/buffer_tests.rs
  src/utils/events.rs
  src/utils/mod.rs
  src/view/mod.rs
Labels: misc, refactor request

#24 Add github action for formatting
  .codecov.yml
  .github/workflows/checkstyle.yml
  src/main.rs
  src/model/app.rs
  src/model/buffer.rs
  src/model/mod.rs
  src/model/tests/buffer_tests.rs
  src/utils/events.rs
  src/utils/mod.rs
  src/view/mod.rs
Labels: misc
